language: node_js
node_js:
- 4
sudo: false
addons:
  firefox: 46.0
before_script:
- npm run test:lint:js
script:
- xvfb-run wct
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [ "x$TRAVIS_TAG" != "x" ] && npm run publish:cdn'
env:
  global:
    # CDN_SECRET
    - secure: CzFjtv/fVK41C4vV7bbXzTEIgtYJbT6hseHxOLrv/Oxan3lkgj0+H3tsHzYjwjXORcRbqlZrURKeh2RZFbduWuXVtqa6Q2O/NSgao5JBtIL0A8hQM8kmGyAMbNJ9sAKJlf4RTE4ORNASwwN9v3l9/kWtD2bL5LbDXxTLy/qYUNIHn4KbUWFiRntXIo9bH2XezLqJPoTo2pNYfgafzuRNJFTo+tMQrKfzMMtByg0p8QFZOJbJd53Z4HpumS7DWO1TUlcByX8rpIWGBeG02SXJHY1JFrl9+H+1q5ZjMlRcUWcU6l2ctCYrPdHGIdR6ANf9Fn1h5xCSup9vDKBDRQbD2gjqD4rdt00fe0jWkwKTD6mEaTs/Rh+0IffU2tgwFj8kayyYOD6vet5etKu8mUf92X7ePIxW31lvSvcU4scOgk5ReMA/ZcCdcZ9GMsaSr64t9i9nEKbdBuZuEdTslDE5l0uGCQPLALYWNWELDqK115f/AP96LaL2H+7jaXw6xM1cSiefHlImiPahu9T+N0ApN8JGUZo7tMkKnCvUXOQQk0XeX8tyA1gJ5V9QpjegIq2HehPwvxjh0ANmCfeG6W6PGALpQRDmYXgp0pXEK066E5Fd7jpJuxizdRQlKwfp3PHYCtIlEPOWm5GoJXKaA2BmcH5ZQj7mx4lY6i2iNihhrYg=
